name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "npm"
    
      - name: Install dependencies
        run: npm install
    
      - name: Run tests
        run: npm test

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v2.0.0
        env:
          STATUS_ICON: ${{ job.status == 'success' && ':white_check_mark:' || ':x:' }}
          STATUS_TEXT: ${{ job.status == 'success' && '成功' || '失敗' }}
          DEPLOY_STATUS: ${{ job.status == 'success' && 'Build and Test が完了しました！' || 'Build and Test に失敗しました。' }}
          COMMIT_URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
        with:
          webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "${{ env.STATUS_ICON }} *${{ env.STATUS_TEXT }}*: ${{ env.DEPLOY_STATUS }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.STATUS_ICON }} *${{ env.STATUS_TEXT }}*: ${{ env.DEPLOY_STATUS }}\n*実行者*: ${{ github.actor }}\n*ブランチ*: ${{ github.ref_name }}\n*コミットメッセージ*: ${{ github.event.head_commit.message }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "<${{ env.COMMIT_URL }}|詳細を確認する>"
                    }
                  ]
                }
              ]
            }